# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 17:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('information', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Places',
            },
        ),
    ]
